/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/mahni/catkin_ws/src/amc_framework/srv/configurationService.srv
 *
 */


#ifndef AMC_FRAMEWORK_MESSAGE_CONFIGURATIONSERVICEREQUEST_H
#define AMC_FRAMEWORK_MESSAGE_CONFIGURATIONSERVICEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace amc_framework
{
template <class ContainerAllocator>
struct configurationServiceRequest_
{
  typedef configurationServiceRequest_<ContainerAllocator> Type;

  configurationServiceRequest_()
    : arm_joint_1(0.0)
    , arm_joint_2(0.0)
    , arm_joint_3(0.0)
    , arm_joint_4(0.0)
    , arm_joint_5(0.0)  {
    }
  configurationServiceRequest_(const ContainerAllocator& _alloc)
    : arm_joint_1(0.0)
    , arm_joint_2(0.0)
    , arm_joint_3(0.0)
    , arm_joint_4(0.0)
    , arm_joint_5(0.0)  {
    }



   typedef double _arm_joint_1_type;
  _arm_joint_1_type arm_joint_1;

   typedef double _arm_joint_2_type;
  _arm_joint_2_type arm_joint_2;

   typedef double _arm_joint_3_type;
  _arm_joint_3_type arm_joint_3;

   typedef double _arm_joint_4_type;
  _arm_joint_4_type arm_joint_4;

   typedef double _arm_joint_5_type;
  _arm_joint_5_type arm_joint_5;




  typedef boost::shared_ptr< ::amc_framework::configurationServiceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::amc_framework::configurationServiceRequest_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct configurationServiceRequest_

typedef ::amc_framework::configurationServiceRequest_<std::allocator<void> > configurationServiceRequest;

typedef boost::shared_ptr< ::amc_framework::configurationServiceRequest > configurationServiceRequestPtr;
typedef boost::shared_ptr< ::amc_framework::configurationServiceRequest const> configurationServiceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::amc_framework::configurationServiceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::amc_framework::configurationServiceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace amc_framework

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/hydro/share/nav_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/hydro/share/sensor_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/hydro/share/actionlib_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/hydro/share/trajectory_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg'], 'brics_actuator': ['/opt/ros/hydro/share/brics_actuator/cmake/../msg'], 'geometry_msgs': ['/opt/ros/hydro/share/geometry_msgs/cmake/../msg'], 'control_msgs': ['/opt/ros/hydro/share/control_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::amc_framework::configurationServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::amc_framework::configurationServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::amc_framework::configurationServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::amc_framework::configurationServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::amc_framework::configurationServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::amc_framework::configurationServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::amc_framework::configurationServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1560ce9ccf0328d1834c5ac5ba0dc6ba";
  }

  static const char* value(const ::amc_framework::configurationServiceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1560ce9ccf0328d1ULL;
  static const uint64_t static_value2 = 0x834c5ac5ba0dc6baULL;
};

template<class ContainerAllocator>
struct DataType< ::amc_framework::configurationServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "amc_framework/configurationServiceRequest";
  }

  static const char* value(const ::amc_framework::configurationServiceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::amc_framework::configurationServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 arm_joint_1\n\
float64 arm_joint_2\n\
float64 arm_joint_3\n\
float64 arm_joint_4\n\
float64 arm_joint_5\n\
";
  }

  static const char* value(const ::amc_framework::configurationServiceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::amc_framework::configurationServiceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.arm_joint_1);
      stream.next(m.arm_joint_2);
      stream.next(m.arm_joint_3);
      stream.next(m.arm_joint_4);
      stream.next(m.arm_joint_5);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct configurationServiceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::amc_framework::configurationServiceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::amc_framework::configurationServiceRequest_<ContainerAllocator>& v)
  {
    s << indent << "arm_joint_1: ";
    Printer<double>::stream(s, indent + "  ", v.arm_joint_1);
    s << indent << "arm_joint_2: ";
    Printer<double>::stream(s, indent + "  ", v.arm_joint_2);
    s << indent << "arm_joint_3: ";
    Printer<double>::stream(s, indent + "  ", v.arm_joint_3);
    s << indent << "arm_joint_4: ";
    Printer<double>::stream(s, indent + "  ", v.arm_joint_4);
    s << indent << "arm_joint_5: ";
    Printer<double>::stream(s, indent + "  ", v.arm_joint_5);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AMC_FRAMEWORK_MESSAGE_CONFIGURATIONSERVICEREQUEST_H
