/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/mahni/catkin_ws/src/amc_framework/srv/configurationService.srv
 *
 */


#ifndef AMC_FRAMEWORK_MESSAGE_CONFIGURATIONSERVICE_H
#define AMC_FRAMEWORK_MESSAGE_CONFIGURATIONSERVICE_H

#include <ros/service_traits.h>


#include <amc_framework/configurationServiceRequest.h>
#include <amc_framework/configurationServiceResponse.h>


namespace amc_framework
{

struct configurationService
{

typedef configurationServiceRequest Request;
typedef configurationServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct configurationService
} // namespace amc_framework


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::amc_framework::configurationService > {
  static const char* value()
  {
    return "1560ce9ccf0328d1834c5ac5ba0dc6ba";
  }

  static const char* value(const ::amc_framework::configurationService&) { return value(); }
};

template<>
struct DataType< ::amc_framework::configurationService > {
  static const char* value()
  {
    return "amc_framework/configurationService";
  }

  static const char* value(const ::amc_framework::configurationService&) { return value(); }
};


// service_traits::MD5Sum< ::amc_framework::configurationServiceRequest> should match 
// service_traits::MD5Sum< ::amc_framework::configurationService > 
template<>
struct MD5Sum< ::amc_framework::configurationServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::amc_framework::configurationService >::value();
  }
  static const char* value(const ::amc_framework::configurationServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::amc_framework::configurationServiceRequest> should match 
// service_traits::DataType< ::amc_framework::configurationService > 
template<>
struct DataType< ::amc_framework::configurationServiceRequest>
{
  static const char* value()
  {
    return DataType< ::amc_framework::configurationService >::value();
  }
  static const char* value(const ::amc_framework::configurationServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::amc_framework::configurationServiceResponse> should match 
// service_traits::MD5Sum< ::amc_framework::configurationService > 
template<>
struct MD5Sum< ::amc_framework::configurationServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::amc_framework::configurationService >::value();
  }
  static const char* value(const ::amc_framework::configurationServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::amc_framework::configurationServiceResponse> should match 
// service_traits::DataType< ::amc_framework::configurationService > 
template<>
struct DataType< ::amc_framework::configurationServiceResponse>
{
  static const char* value()
  {
    return DataType< ::amc_framework::configurationService >::value();
  }
  static const char* value(const ::amc_framework::configurationServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AMC_FRAMEWORK_MESSAGE_CONFIGURATIONSERVICE_H
