(cl:defpackage amc_framework-srv
  (:use )
  (:export
   "CONFIGURATIONSERVICE"
   "<CONFIGURATIONSERVICE-REQUEST>"
   "CONFIGURATIONSERVICE-REQUEST"
   "<CONFIGURATIONSERVICE-RESPONSE>"
   "CONFIGURATIONSERVICE-RESPONSE"
  ))

